edited transfer

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -8,17 +8,20 @@ fi
 
 
 # Assign arguments to variables
-file_path="$1"
-server_ip="$2"
-username="$3"
-ssh_key_path="$4"
+
+file_path=$1
+server_ip=$2
+username=$3
+ssh_key_path=$4
+
+# Disable strict host key checking
+scp -0 "StrictHostkeyChecking=no" -i "$file_path_ssh_key" "$path_to_file" "$username@$ip:~/"
 
 
-# Disable strict host key checking (not recommended for production)
-ssh -o StrictHostKeyChecking=no -i "$ssh_key_path" $username@$server_ip "mkdir -p ~/"
-
-
-# Transfer the file using scp with progress bar
-scp -i "$ssh_key_path" "$file_path" $username@$server_ip:~/ &> /dev/null && echo "File transferred successfully!" || echo "Failed to transfer file."
-
-exit 0
+#checking if transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILW WAS TRANSFERRED SUCCESSFUL"
+else
+	echo"FILE TRANSFER FAILED"
+fi
